name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "c1687981-cb14-4290-b4f7-1ee3ff4e9a91"      # 替换为你创建的数据库 ID

